### ISSUE TITLE
eleventy-plugin-sass breaks build and is deprecated - cannot npm install

### ISSUE THREAD

**Issue by ieugen** [bigskysoftware/htmx#1153]
Hello, 

I am trying to contribute to htmx and I cloned the project and `npm install` 

I get an error that I tracked to -    "eleventy-plugin-sass": "^1.2.0" .

Removing the package from devDependencies, I can `npm install` .
I have python3. I am on Debian testing.

The page mentions https://www.npmjs.com/package/eleventy-plugin-sass :

> This package has been deprecated
Author message:
Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /home/ieugen/proiecte/htmx/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c -- node scripts/build.js
npm ERR! Building: /home/ieugen/.nvm/versions/node/v16.18.1/bin/node /home/ieugen/proiecte/htmx/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/home/ieugen/.nvm/versions/node/v16.18.1/bin/node',
npm ERR! gyp verb cli   '/home/ieugen/proiecte/htmx/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.18.1 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/ieugen/proiecte/htmx/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/ieugen/proiecte/htmx/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/ieugen/proiecte/htmx/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/ieugen/proiecte/htmx/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/ieugen/proiecte/htmx/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/ieugen/proiecte/htmx/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/ieugen/proiecte/htmx/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/ieugen/proiecte/htmx/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/ieugen/proiecte/htmx/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/ieugen/proiecte/htmx/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/ieugen/proiecte/htmx/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/ieugen/proiecte/htmx/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:402:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:458:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:301:12)
npm ERR! gyp ERR! System Linux 6.0.0-5-amd64
npm ERR! gyp ERR! command "/home/ieugen/.nvm/versions/node/v16.18.1/bin/node" "/home/ieugen/proiecte/htmx/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/ieugen/proiecte/htmx/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.18.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

**Comment by 1cg** [comment]
see pull request, closing for now, will try to upgrade eleventy for htmx 2.0 😑
