### ISSUE TITLE
hx-sync causes `elt is null` errors

### ISSUE THREAD

**Issue by egtann** [bigskysoftware/htmx#2432]
### The error

In Firefox v124:

```
Uncaught TypeError: elt is null
    getInternalData https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:715
    issueAjaxRequest https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:4068
    processVerbs https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2525
    delayed https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2428
    setTimeout handler*eventListener https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2428
    addEventListener https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2443
    forEach https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:746
    addEventListener https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2366
    addTriggerHandler https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2577
    processVerbs https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2519
    processVerbs https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2518
    forEach https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:746
    processVerbs https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2512
    initNode https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2766
    processNode https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2804
    forEach https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:746
    processNode https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:2804
    <anonymous> https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:4875
    ready https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:4838
    htmx https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:4871
    <anonymous> https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js:4911
```

In Chromium v123:

```
htmx.js:715 Uncaught TypeError: Cannot read properties of null (reading 'htmx-internal-data')
    at getInternalData (htmx.js:715:19)
    at issueAjaxRequest (htmx.js:4068:17)
    at htmx.js:2525:13
    at htmx.js:2428:71
```

### To Reproduce

```
<head>
    <script src="https://unpkg.com/htmx.org@2.0.0-beta1/dist/htmx.js"></script>
</head>
<input name="name" hx-post="" hx-trigger="input changed delay:500ms" hx-sync="abort"/>
```

Type anything into the input, wait 500ms, and you'll see the error.

Note that `hx-sync` can be any value defined [in the docs](https://htmx.org/attributes/hx-sync/) to replicate the issue.

I've confirmed that it's happening in both v1.9.11 and v2.0.0-beta1.

**Comment by egtann** [comment]
I neglected to read the docs. `hx-sync` needs a selector before the strategy, and it works fine. A nicer error indicating that the value in hx-sync is formatted incorrectly would have helped, so I'll leave this issue open for the possibility.

**Comment by luontola** [comment]
There would be need for two error messages:
- When the hx-sync value is in incorrect format
- When the CSS selector doesn't find an element
